---
- name: Configure elasticsearch.yml file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_etc_dir_path }}/elasticsearch.yml"
  notify: Restart Elasticsearch

- name: Configure JVM heap size
  template:
    path: heap-size.j2
    dest: /etc/elasticsearch/jvm.options.d/heap-size
    owner: root
    group: elasticsearch
    mode: 0660
  notify: Restart Elasticsearch
